"""empty message

Revision ID: b6f61b196b53
Revises: cf2fe073ef60
Create Date: 2019-05-06 00:17:29.220468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f61b196b53'
down_revision = 'cf2fe073ef60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('image', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_image_timestamp'), 'image', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'image', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_index(op.f('ix_image_timestamp'), table_name='image')
    op.drop_column('image', 'timestamp')
    op.drop_column('image', 'owner_id')
    # ### end Alembic commands ###
